# Numpy Basics <hr style = "border:2.5px solid #0000FF"></hr>

<b> Byron Mojica </b>
<br> Comptech Student T09

In [98]:
#Import and packages
import numpy as np
from statistics import multimode
from scipy import stats

In [ ]:
my_array= np.array ([1,2,3])
my_array

array([1, 2, 3])

In [ ]:
np.shape(my_array)

(3,)

# 2D Array <hr style = "border:2.5px solid #0000FF"></hr>

In [ ]:
my_array = np.array ([
        [1,2,3],
        [4,5,6]
        ])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.shape(my_array)

(2, 3)

In [ ]:
t_array = my_array.T
t_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.shape(t_array)

(3, 2)

# Measures of Central Tendency <hr style = "border:2.5px solid #0000FF"></hr>

In [ ]:
# Jaguar vs Panther
resistance = np.array ([
    [10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5, 11, 10.4, 3, 9.8],
    [10.1, 11, 9.1, 20, 9.2, 10.8, 9.9, 9.2, 9.1, 9.1, np.nan]
])

print (resistance)

[[10.6  9.1  9.3  9.8 10.5 10.4  9.5 11.  10.4  3.   9.8]
 [10.1 11.   9.1 20.   9.2 10.8  9.9  9.2  9.1  9.1  nan]]


In [ ]:
np.shape(resistance)

(2, 11)

In [ ]:
res_mean = np.nanmean(resistance, axis = 1)
res_mean

array([ 9.4 , 10.75])

In [ ]:
print("Jaguar Mean:" + str ((res_mean[0]).round(2))+ " ohms")

Jaguar Mean:9.4 ohms


In [ ]:
print(f'Jaguar:{res_mean[0]:.2f} ohms')
print(f'Panther:{res_mean[1]:.2f} ohms')

Jaguar:9.40 ohms
Panther:10.75 ohms


In [ ]:
res_median = np.nanmedian(resistance, axis = 1)
res_median

array([9.8 , 9.55])

In [ ]:
print(f'Jaguar: {res_median[0]:.2f} ohms')
print(f'Panther: {res_median[1]:.2f} ohms')

Jaguar: 9.80 ohms
Panther: 9.55 ohms


In [99]:
res_mode = stats.mode (resistance, axis = 1)
res_mode

ModeResult(mode=array([9.8, 9.1]), count=array([2, 3]))

In [100]:
jag_res = resistance[0]

print("Jaguar Mode")
for i in multimode (jag_res):
    print(f'{i} ohms')

Jaguar Mode
9.8 ohms
10.4 ohms


# MEASURES OF VARIABILITY <hr style = "border:2.5px solid #0000FF"></hr>

In [101]:
# Jaguar vs Panther
resistance = np.array ([
    [10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5, 11, 10.4, 3, 9.8],
    [10.1, 11, 9.1, 20, 9.2, 10.8, 9.9, 9.2, 9.1, 9.1, np.nan]
])

print (resistance)

[[10.6  9.1  9.3  9.8 10.5 10.4  9.5 11.  10.4  3.   9.8]
 [10.1 11.   9.1 20.   9.2 10.8  9.9  9.2  9.1  9.1  nan]]


In [103]:
# Range

res_max = np.nanmax (resistance, axis = 1)
res_min = np.nanmin (resistance, axis = 1)

res_range = res_max - res_min
res_range

array([ 8. , 10.9])

In [105]:
print(f'Jaguar Range: {res_range[0]:.2f} ohms')
print(f'Panther Range: {res_range[1]:.2f} ohms')

Jaguar Range: 8.00 ohms
Panther Range: 10.90 ohms


In [114]:
# IQR
res_Q1 = np.nanpercentile (resistance,25,axis=1)
res_Q1

array([9.4  , 9.125])

In [115]:
# IQR
res_Q3 = np.nanpercentile (resistance,75,axis=1)
res_Q3

array([10.45 , 10.625])

In [117]:
print(f'Jaguar IQR: {res_Q3[0] - res_Q1[0]:.2f} ohms')
print(f'Panther IQR: {res_Q3[1] - res_Q1[1]:.2f} ohms')

Jaguar IQR: 1.05 ohms
Panther IQR: 1.50 ohms


In [123]:
res_var = np.nanvar(resistance, ddof = 1, axis = 1)

print(f'Jaguar Variance: {res_var[0]:.2f} ohms')
print(f'Panther Variance: {res_var[1]:.2f} ohms')

Jaguar Variance: 4.86 ohms
Panther Variance: 11.08 ohms


In [125]:
res_std = np.nanstd(resistance, ddof = 1, axis = 1)

print(f'Jaguar STD: {res_std[0]:.2f} ohms')
print(f'Panther STD: {res_std[1]:.2f} ohms')

Jaguar STD: 2.20 ohms
Panther STD: 3.33 ohms
